### ISSUE TITLE
Add More Radios

### ISSUE THREAD

**Issue by hamidrabedi** [seyedmahdi4/radio#2]
More channels and radios (like RadioJavan) and ability to expand or collapse radios to see all channels with their playing songs

**Comment by seyedmahdi4** [comment]
سلام. ایده ی خوبیه ولی خب من بیشتر هدفم گلچین کردن بودش. و رادیو هم سرورش ایرانه برای دسترسی ساده تر. اگه بخوایم تو فاز لیست کردن و ادد کردن رادیو های جهانی بریم ممکنه مشکلات فیلتر و تحریم هم اذیتمون کنه.در نهایت این شروع ماجراست. از ایده ها استقبال میکنم و آینده اگه سرم خلوت شه پیاده میکنم. فعلا در گیر نسخه ی وب و اندروید هستم
