### ISSUE TITLE
Volume change doesn't work

### ISSUE THREAD

**Issue by hamidrabedi** [seyedmahdi4/radio#3]
The UP and DOWN keys on Windows with git bash don't work.

**Comment by seyedmahdi4** [comment]
من دسترسی ندارم که تست کنم ولی ۲ تا سولوشن به نظرم میرسه
یکی اینکه دکمه های - + رو هم در کنار up  down اضافه کنیم
دوم اینکه مقدار عددی دکمه ها رو دربیاریم. خط 98 اگه این ۲ لاین رو اضافه کنید و دکمه ی آپ رو بزنید و ببینید چی برمیگردونه و توی تست مجدد دکمه ی داون که ما مقدار عددی up و down رو اضافه کنیم

print(key)
time.sleep(10)

فعلا مشکلی سمت ویندوز گزارش نشده ولی اگه ببینم مشکلات زیاد میشه میشه سمت لایبری های تمیز تر هم رفت

توی cmd هم تست کردید؟

**Comment by hamidrabedi** [comment]
هیچ چیزی چاپ نمیشه
توی cmd, powershell مشکلی نداره

**Comment by seyedmahdi4** [comment]
اگه چیزی چاپ نمیشه یعنی دکمه رو شناسایی نمیکنه.
میتونیم روی دکمه ی + و − هم اعمال کنیم

**Comment by hamidrabedi** [comment]
بله اون هارو تست کردم میشه اضافه کرد اوکیه

ولی یه باگ عجیب دیگه که خوردم روی power shell, cmd نمیتونه دکمه های num pad رو شناسایی کنه ولی توی bash این یه مورد اوکیه:

```
    while True:
        key = stdscr.getch()
        if key == 27:  # Escape key
            break
        elif key == curses.KEY_UP:
            volume = handle_volume_change(player, 5)
        elif key == 43:
            volume = handle_volume_change(player, 5)
        elif key == curses.KEY_DOWN:
            volume = handle_volume_change(player, -5)
        elif key == 45:
            volume = handle_volume_change(player, -5)
```

**Comment by seyedmahdi4** [comment]
دکمه های نام پد شماره key های متفاوتی دارن؟ عجیبه

**Comment by hamidrabedi** [comment]
نه یکسانه و توی bash درست جواب میده
ولی توی cmd, ps درست جواب نمیده.
