### ISSUE TITLE
Curses error when window is too small

### ISSUE THREAD

**Issue by hamidrabedi** [seyedmahdi4/radio#5]
I get this error when i try to run with a small window:
```
EROOR: addwstr() returned ERR
```
only raises when window is too small vertically:

![image](https://github.com/seyedmahdi4/radio/assets/92696830/814198d8-1d17-43ad-97db-d4be3462af44)

![image](https://github.com/seyedmahdi4/radio/assets/92696830/96b6b1a9-dddd-45b4-942e-3139903fcdd2)

**Comment by seyedmahdi4** [comment]
Hello. I fixed this issue in last night's update. Can you test again?

**Comment by hamidrabedi** [comment]
Yes that one is fixed.
